// ABOUTME: Sentinel that lets a hand-written copyWith tell "argument omitted"
// ABOUTME: apart from "argument explicitly set to null" on nullable fields.

/// Default for a nullable `copyWith` parameter.
///
/// A plain `value ?? this.value` cannot clear a nullable field: passing
/// `null` is indistinguishable from omitting the argument, so the old value
/// survives and the call silently does nothing. These state classes were
/// generated by freezed before the Dart 3.13 migration, and freezed's
/// `copyWith` cleared the field — call sites such as `copyWith(error: null)`
/// rely on that. Comparing against this sentinel with [identical] keeps that
/// behaviour.
const Object unsetCopyWithArgument = Object();
