linter:
  rules:
    - always_put_required_named_parameters_first
    - always_use_package_imports
    - avoid_final_parameters
    - avoid_js_rounded_ints
    - avoid_redundant_argument_values
    - avoid_returning_null_for_void
    - annotate_overrides
    - avoid_escaping_inner_quotes
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_void_async
    - await_only_futures
    - combinators_ordering
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - eol_at_end_of_file
    - library_prefixes
    - library_private_types_in_public_api
    - literal_only_boolean_expressions
    - missing_code_block_language_in_doc_comment
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_leading_underscores_for_library_prefixes
    - no_logic_in_create_state
    - no_runtimeType_toString
    - noop_primitive_operations
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_int_literals
    - prefer_single_quotes
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_lambdas
    - unnecessary_late
    - use_colored_box
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_to_list_in_spreads
    - unnecessary_underscores
    - unrelated_type_equality_checks
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors
    - use_rethrow_when_possible
    - use_super_parameters
    - use_string_buffers
    - use_string_in_part_of_directives
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
    - valid_regexps
    - void_checks
