linter:
  rules:
    - annotate_overrides
    - directives_ordering
    - prefer_collection_literals
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - unnecessary_breaks
