linter:
  rules:
    - always_put_required_named_parameters_first
    - avoid_final_parameters
    - avoid_js_rounded_ints
    - avoid_returning_null_for_void
    - annotate_overrides
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_void_async
    - await_only_futures
    - combinators_ordering
    - directives_ordering
    - eol_at_end_of_file
    - prefer_collection_literals
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_constructor_name
    - use_colored_box
