linter:
  rules:
    - unnecessary_await_in_return
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
