linter:
  rules:
    - unnecessary_await_in_return
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - use_key_in_widget_constructors
