linter:
  rules:
    - always_put_required_named_parameters_first
    - avoid_final_parameters
    - avoid_js_rounded_ints
    - annotate_overrides
    - directives_ordering
    - prefer_collection_literals
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - unnecessary_breaks
    - use_colored_box
