#!/usr/bin/env bash
# App-owned Hive opens must use HiveBoxOpener so merged tests can observe them.
# Direct production calls are frozen at zero by this list ratchet (#9053).

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RATCHET_LABEL="direct_hive_opens"
BASELINE_FILE="$SCRIPT_DIR/baseline/direct_hive_opens.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/direct_hive_opens.txt"
BASE_REF="${DIRECT_HIVE_OPENS_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${DIRECT_HIVE_OPENS_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="DIRECT_HIVE_OPENS_ALLOW_NO_BASE"
NEW_HINT="Route app-owned box opens through HiveBoxOpener so the merged test harness can observe in-flight opens. See #9053."
STALE_HINT="A direct Hive open was removed."
FOOTER="Direct Hive.openBox and Hive.openLazyBox calls in production are frozen at zero. Use HiveBoxOpener instead. See #9053."

emit_current() {
  grep -rlE 'Hive\.(openBox|openLazyBox)' \
    "$MOBILE_DIR/lib" "$MOBILE_DIR"/packages/*/lib \
    --include='*.dart' 2>/dev/null \
  | while IFS= read -r file; do
      [[ "$file" == "$MOBILE_DIR/lib/services/hive_box_opener.dart" ]] && continue
      count="$(awk -f "$SCRIPT_DIR/lib/dart_code_only.awk" "$file" \
        | grep -oE 'Hive\.(openBox|openLazyBox)[<(]' | grep -c . || true)"
      if [[ "$count" -gt 0 ]]; then
        printf '%s\n' "${file#"$MOBILE_DIR"/}"
      fi
    done | sort -u
}

print_baseline_header() {
  cat <<'EOF'
# Frozen zero baseline (#9053): production files that call Hive.openBox or
# Hive.openLazyBox outside HiveBoxOpener. Generated by
# scripts/check_direct_hive_opens.sh. This list must remain empty.
EOF
}

# shellcheck source=lib/list_ratchet.sh
source "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
