#!/usr/bin/env bash
# Issue #7278: unsettled scroll-then-interact test sites are frozen at ZERO.
# Assertions and widget reads are allowed, but do not clear pending layout.
# The AST detector follows ordered same-file helpers and conditional paths;
# only a completed pump on the same tester clears an outstanding scroll.
# No inline escape hatch. Fix the test instead of adding a baseline entry.
set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
RATCHET_LABEL="bare_scroll_interaction"
BASELINE_FILE="${BARE_SCROLL_INTERACTION_BASELINE_FILE:-$SCRIPT_DIR/baseline/bare_scroll_interaction.txt}"
BASELINE_REPO_PATH="${BARE_SCROLL_INTERACTION_BASELINE_REPO_PATH:-mobile/scripts/baseline/bare_scroll_interaction.txt}"
BASE_REF="${BARE_SCROLL_INTERACTION_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${BARE_SCROLL_INTERACTION_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="BARE_SCROLL_INTERACTION_ALLOW_NO_BASE"
DART_BIN="${BARE_SCROLL_INTERACTION_DART:-dart}"
SCAN_DIRS="${BARE_SCROLL_INTERACTION_SCAN_DIRS:-test integration_test packages}"

NEW_HINT="Use scrollUntilTappable before a viewport-sensitive interaction, or await a pump on the same tester after the bare scroll. Assertions do not settle layout. See .claude/rules/testing.md and #7278."
STALE_HINT="An unsettled scroll interaction was removed."
FOOTER="Scroll-then-interact sites without a completed frame are frozen at zero.
Inspect sites from mobile/ with:
  dart scripts/lib/bare_scroll_interaction_detector.dart test integration_test packages --path-prefix . --detail"

emit_current() {
  (
    cd "$MOBILE_DIR"
    # shellcheck disable=SC2086
    "$DART_BIN" scripts/lib/bare_scroll_interaction_detector.dart \
      $SCAN_DIRS --path-prefix "$MOBILE_DIR"
  ) | LC_ALL=C sort
}

print_baseline_header() {
  cat <<'EOF'
# Frozen at ZERO: unsettled scroll-then-interact sites in test, integration_test
# and packages/*/test, including same-file helper calls (#7278).
# Format: relpath<TAB>count. Generated by check_bare_scroll_interaction.sh.
# This list is intentionally empty. Fix the test instead of regenerating it.
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
