#!/usr/bin/env bash
# Service-suite coverage guard (#8755): every integration_test/e2e suite must
# either run in the Linux service workflow or appear in the shrink-only
# exclusion manifest with a reason.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="${SERVICE_SUITE_MOBILE_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
REPO_ROOT="$(cd "$MOBILE_DIR/.." && pwd)"
WORKFLOW="${SERVICE_SUITE_WORKFLOW:-$REPO_ROOT/.github/workflows/mobile_service_integration_tests.yaml}"
E2E_DIR="${SERVICE_SUITE_E2E_DIR:-$MOBILE_DIR/integration_test/e2e}"

RATCHET_LABEL="service_suite_coverage"
BASELINE_FILE="${SERVICE_SUITE_BASELINE_FILE:-$SCRIPT_DIR/baseline/service_suite_exclusions.txt}"
BASELINE_REPO_PATH="mobile/scripts/baseline/service_suite_exclusions.txt"
BASE_REF="${SERVICE_SUITE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${SERVICE_SUITE_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="SERVICE_SUITE_ALLOW_NO_BASE"
NEW_HINT="Run each new suite in the Linux service workflow, or explain why it cannot run there. Exclusions may not grow versus origin/main."
STALE_HINT="An excluded suite is now executed by the workflow or no longer exists."
FOOTER="Every integration_test/e2e suite must be run by the Linux service
workflow or remain in the reason-bearing, shrink-only exclusion manifest.
See issue #8755."

fail() {
  echo "FAIL [service_suite_coverage]: $*" >&2
  exit 1
}

[ -f "$WORKFLOW" ] || fail "workflow not found: $WORKFLOW"
[ -d "$E2E_DIR" ] || fail "suite directory not found: $E2E_DIR"
[ -f "$BASELINE_FILE" ] || fail "exclusion manifest not found: $BASELINE_FILE"

anchor='- name: 🚀 Run service integration tests'
anchor_count="$(grep -cF -- "$anchor" "$WORKFLOW" || true)"
[ "$anchor_count" -eq 1 ] || fail "expected exactly one '$anchor' step, found $anchor_count"

step_tail="$(sed -n "/$anchor/,\$p" "$WORKFLOW")"
loop_start_count="$(printf '%s\n' "$step_tail" | grep -cE '^[[:space:]]*for suite in \\$' || true)"
loop_end_count="$(printf '%s\n' "$step_tail" | grep -cE '; do[[:space:]]*$' || true)"
[ "$loop_start_count" -eq 1 ] || fail "expected exactly one service-suite loop start, found $loop_start_count"
[ "$loop_end_count" -eq 1 ] || fail "expected exactly one service-suite loop end, found $loop_end_count"

loop_body="$(printf '%s\n' "$step_tail" | sed -n '/^[[:space:]]*for suite in \\$/,/; do[[:space:]]*$/p')"
run_list_raw="$(printf '%s\n' "$loop_body" | grep -oE 'integration_test/e2e/[A-Za-z0-9_]+_test\.dart' || true)"
[ -n "$run_list_raw" ] || fail "service-suite loop contains no E2E suite paths"

duplicate_runs="$(printf '%s\n' "$run_list_raw" | sort | uniq -d)"
[ -z "$duplicate_runs" ] || fail "workflow runs duplicate suite path(s):
$(printf '%s\n' "$duplicate_runs" | sed 's/^/  /')"
RUN_LIST="$(printf '%s\n' "$run_list_raw" | sort -u)"

while IFS= read -r suite; do
  [ -f "$MOBILE_DIR/$suite" ] || fail "workflow suite does not exist: $suite"
done <<< "$RUN_LIST"

manifest_entries="$(sed -e '/^[[:space:]]*#/d' -e '/^[[:space:]]*$/d' "$BASELINE_FILE")"
invalid_entries="$(printf '%s\n' "$manifest_entries" | grep -vE '^integration_test/e2e/[A-Za-z0-9_]+_test\.dart[[:space:]]+#[[:space:]]*[^[:space:]].*$' || true)"
[ -z "$invalid_entries" ] || fail "every exclusion must be a canonical suite path followed by a nonempty '# reason':
$(printf '%s\n' "$invalid_entries" | sed 's/^/  /')"

manifest_paths="$(printf '%s\n' "$manifest_entries" | sed 's/[[:space:]]*#.*//; s/[[:space:]]*$//')"
duplicate_exclusions="$(printf '%s\n' "$manifest_paths" | grep -v '^$' | sort | uniq -d)"
[ -z "$duplicate_exclusions" ] || fail "exclusion manifest contains duplicate path(s):
$(printf '%s\n' "$duplicate_exclusions" | sed 's/^/  /')"
MANIFEST_PATHS="$(printf '%s\n' "$manifest_paths" | grep -v '^$' | sort -u || true)"

overlap="$(comm -12 <(printf '%s\n' "$RUN_LIST") <(printf '%s\n' "$MANIFEST_PATHS") | grep -v '^$' || true)"
[ -z "$overlap" ] || fail "suite path(s) appear in both the workflow and exclusion manifest:
$(printf '%s\n' "$overlap" | sed 's/^/  /')"

emit_current() {
  find "$E2E_DIR" -maxdepth 1 -type f -name '*_test.dart' -print \
    | sed "s#^$MOBILE_DIR/##" \
    | sort -u \
    | comm -23 - <(printf '%s\n' "$RUN_LIST")
}

print_baseline_header() {
  cat <<'EOF'
# Frozen exclusion list: integration_test/e2e suites that cannot run in the
# Linux service integration workflow. Generated by
# scripts/check_service_suite_coverage.sh. The set may only SHRINK; every entry
# must retain a trailing '# reason'. Issue: #8755.
EOF
}

# shellcheck source=lib/list_ratchet.sh
. "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
