#!/usr/bin/env bash
# Legacy design-library import guard (#8916). Frozen at ZERO across mobile/lib,
# mobile/test, mobile/integration_test, mobile/packages and mobile/tools:
# no Dart file may import `package:flutter/material.dart` or
# `package:flutter/cupertino.dart`.
#
# Why this needs a guard rather than a note in a rules file. Both libraries
# still exist in Flutter 3.47.2, so a reintroduced import compiles, analyzes and
# tests clean — right up to the point where two `ThemeData`s, two `AppBar`s or
# two `MaterialLocalizations` meet. The failure then reads as an unrelated type
# error in whichever file happens to sit at the seam, and the actual mistake is
# an import line in a different file entirely. Nothing else in the toolchain
# notices: `depend_on_referenced_packages` is satisfied because `flutter` is a
# dependency of every package here, and no ratchet in this directory reads
# import URIs.
#
# The scan matches the directive shape (`import '...'` / `export '...'` at the
# start of a line), not the mere presence of the path, so prose that names the
# legacy library — this file, the comment on appLocalizationsDelegates — is not
# a hit. String literals are deliberately NOT stripped: tools/generate_tests.dart
# emits an import line into a template, and the tests it writes would otherwise
# land pre-broken with nothing to catch it.
#
# NOT a rule against Flutter: `package:flutter/widgets.dart`, `foundation.dart`,
# `services.dart`, `painting.dart` and friends stay in the framework and are the
# right import for anything that never touches a design-system widget.
#
# Frozen at zero: fix the import rather than regenerating the baseline. The
# replacements are `package:material_ui/material_ui.dart` and
# `package:cupertino_ui/cupertino_ui.dart`.
# Usage:
#   bash mobile/scripts/check_legacy_design_imports.sh
#   (cd mobile && bash scripts/check_legacy_design_imports.sh)

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="legacy_design_imports"
PATH_PREFIX="${LEGACY_DESIGN_IMPORTS_PATH_PREFIX:-$MOBILE_DIR}"
BASELINE_FILE="${LEGACY_DESIGN_IMPORTS_BASELINE_FILE:-$SCRIPT_DIR/baseline/legacy_design_imports.txt}"
BASELINE_REPO_PATH="${LEGACY_DESIGN_IMPORTS_BASELINE_REPO_PATH:-mobile/scripts/baseline/legacy_design_imports.txt}"
BASE_REF="${LEGACY_DESIGN_IMPORTS_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${LEGACY_DESIGN_IMPORTS_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="LEGACY_DESIGN_IMPORTS_ALLOW_NO_BASE"

# Scan roots, relative to MOBILE_DIR.
SCAN_DIRS="${LEGACY_DESIGN_IMPORTS_SCAN_DIRS:-lib test integration_test packages tools}"

DETECT_RE="^[[:space:]]*(import|export)[[:space:]]+'package:flutter/(material|cupertino)\.dart'"

NEW_HINT="Material and Cupertino ship as pub packages now: import package:material_ui/material_ui.dart or package:cupertino_ui/cupertino_ui.dart. A file that needs no design-system widget should import package:flutter/widgets.dart instead. Mixing the two libraries gives you two incompatible ThemeData/MaterialLocalizations types and the error surfaces far from the import. See #8916."
STALE_HINT="A file dropped its legacy Material/Cupertino import."
FOOTER="Imports of package:flutter/material.dart and package:flutter/cupertino.dart
are frozen at zero (#8916). Both libraries still exist in Flutter 3.47.2, so a
reintroduced import compiles and only fails where the two type universes meet.
List the sites with:
  cd mobile && grep -rnE \"^[[:space:]]*(import|export)[[:space:]]+'package:flutter/(material|cupertino)[.]dart'\" lib test integration_test packages tools"

# Print "relpath<TAB>count" for every Dart file carrying a legacy design import.
emit_current() {
  (
    cd "$MOBILE_DIR"
    # shellcheck disable=SC2086
    find $SCAN_DIRS \
      -type f -name '*.dart' \
      -not -path '*/.dart_tool/*' \
      -not -path '*/build/*' \
      -print0 2>/dev/null
  ) | while IFS= read -r -d '' f; do
      count="$(grep -cE "$DETECT_RE" "$MOBILE_DIR/$f" || true)"
      count="${count//[[:space:]]/}"
      if [[ "${count:-0}" -gt 0 ]]; then
        printf '%s\t%s\n' "$f" "$count"
      fi
    done \
  | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<EOF
# Frozen baseline: Dart files under mobile/{lib,test,integration_test,packages,
# tools} importing package:flutter/material.dart or package:flutter/cupertino.dart
# (format: relpath<TAB>count). Generated by
# scripts/check_legacy_design_imports.sh.
#
# Frozen at ZERO (#8916). Any entry here is a regression: change the import to
# package:material_ui/material_ui.dart, package:cupertino_ui/cupertino_ui.dart,
# or package:flutter/widgets.dart when no design-system widget is involved —
# do not regenerate the baseline.
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
