#!/usr/bin/env bash
# Riverpod listener self-invalidation guard (#9266), frozen at zero.
#
# A callback installed with addListener must publish changed state without
# rebuilding the provider that owns the registration. Calling
# ref.invalidateSelf() from that callback reruns the provider, tears down and
# reinstalls its listener, and resets local version counters. Prefer a
# notifier/cubit, a StreamProvider, or an explicit version provider.

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DART_BIN="${LISTENER_INVALIDATE_SELF_DART:-dart}"
TAB="$(printf '\t')"

RATCHET_LABEL="listener_invalidate_self"
BASELINE_FILE="${LISTENER_INVALIDATE_SELF_BASELINE_FILE:-$SCRIPT_DIR/baseline/listener_invalidate_self.txt}"
BASELINE_REPO_PATH="${LISTENER_INVALIDATE_SELF_BASELINE_REPO_PATH:-mobile/scripts/baseline/listener_invalidate_self.txt}"
BASE_REF="${LISTENER_INVALIDATE_SELF_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${LISTENER_INVALIDATE_SELF_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="LISTENER_INVALIDATE_SELF_ALLOW_NO_BASE"
NEW_HINT="An addListener callback must publish changed state, not call ref.invalidateSelf(), which reinstalls the listener and resets local state. Prefer a notifier/cubit, StreamProvider, or an explicit monotonically increasing value provider. See #9266."
STALE_HINT="The zero baseline has no entries to remove."
FOOTER="Service-listener callbacks that invalidate their own provider are frozen at zero. Inspect sites with: dart run scripts/lib/listener_invalidate_self_detector.dart lib --path-prefix . --detail"

emit_current() {
  (
    cd "$MOBILE_DIR"
    "$DART_BIN" run scripts/lib/listener_invalidate_self_detector.dart lib \
      --path-prefix "$MOBILE_DIR"
  ) | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: addListener callbacks under mobile/lib that call
# ref.invalidateSelf() (format: relpath<TAB>count). Generated by
# scripts/check_listener_invalidate_self.sh from the Dart AST detector.
#
# Frozen at ZERO (#9266). Any entry is a regression: publish the changed state
# instead of rebuilding the provider that owns the listener registration.
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
