#!/usr/bin/env bash
# Freeze each missing ICU cardinal category (#7755), not totals per locale.
# Regenerate only after fixing gaps; reasons survive baseline regeneration.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
RATCHET_LABEL="plural_category_floor"
BASELINE_FILE="$SCRIPT_DIR/baseline/plural_category_gaps.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/plural_category_gaps.txt"
BASE_REF="${PLURAL_CATEGORY_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${PLURAL_CATEGORY_FLOOR_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="PLURAL_CATEGORY_FLOOR_ALLOW_NO_BASE"
NEW_HINT="A plural block lost a category selected by the pinned intl rules. Add appropriate fluent-reviewed wording; do not machine-generate grammatical forms. Baseline additions cannot excuse new gaps. See #7755 and LOCALIZATION_STYLE_GUIDE.md."
STALE_HINT="A plural-category gap was fixed or removed."
FOOTER="Each locale/message/block/category gap may only shrink. Intentional invariant wording and declined large-number forms carry baseline reasons. #7755 remains the translation tracking issue."
emit_current() {
  # Explicit failure propagation prevents a parser error from becoming an empty baseline.
  local current
  current="$(cd "$MOBILE_DIR" && dart run scripts/lib/plural_category_detector.dart lib/l10n)" || return 1
  printf '%s\n' "$current"
}
print_baseline_header() {
  cat <<'EOF'
# Missing cardinal categories sampled from the pinned intl rules (#7755).
# Format: locale/message/selector:occurrence[/branch/selector:occurrence]/category
# Set may only SHRINK; fixes cannot mask new omissions elsewhere.
# Generated by check_plural_category_floor.sh; UPDATE_BASELINE preserves reasons.
# Probes integers 0..1000, decimal samples at precision 1/2, and 1M/2M.
# Sample coverage is not an exhaustive proof for future CLDR releases.
# Unannotated gaps remain tracked translation work in #7755, requiring fluent review.
# declined: large-number many falls back to other on current surfaces; revisit
# when a surface needs distinct large-number wording. No detector exemptions.
# intentional: invariant wording is not evidence of a grammatical error.
EOF
}
# shellcheck source=lib/list_ratchet.sh
source "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
