import 'package:flutter/widgets.dart';
import 'package:material_ui/material_ui.dart' show GlobalMaterialLocalizations;
import 'package:openvine/l10n/generated/app_localizations.dart';

export 'package:openvine/l10n/generated/app_localizations.dart';

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}

/// Every delegate an app-root widget in this app registers.
///
/// [AppLocalizations.localizationsDelegates] is generated by `flutter
/// gen-l10n`, which has no notion of `material_ui` and always emits
/// `flutter_localizations`' `Global*Localizations`. Those satisfy the
/// framework's `MaterialLocalizations`, which since #8916 is a different type
/// from the one `material_ui` widgets look up. On its own, that list leaves
/// non-English locales without a supported `material_ui`
/// `MaterialLocalizations` delegate. Widgets such as `DiVineAppBar` read
/// `MaterialLocalizations.backButtonTooltip` unconditionally, so those
/// locales would throw when rendering navigation semantics.
///
/// The generated framework entries stay untouched so regeneration remains
/// deterministic. The appended delegates provide the corresponding
/// `material_ui` types used by the app.
const List<LocalizationsDelegate<dynamic>> appLocalizationsDelegates =
    <LocalizationsDelegate<dynamic>>[
      ...AppLocalizations.localizationsDelegates,
      ...GlobalMaterialLocalizations.delegates,
    ];
