import 'package:flutter/widgets.dart';
import 'package:material_ui/material_ui.dart' show GlobalMaterialLocalizations;
import 'package:openvine/l10n/generated/app_localizations.dart';

export 'package:openvine/l10n/generated/app_localizations.dart';

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}

/// Every delegate an app-root widget in this app registers.
///
/// [AppLocalizations.localizationsDelegates] is generated by `flutter
/// gen-l10n`, which has no notion of `material_ui` and always emits
/// `flutter_localizations`' `Global*Localizations`. Those satisfy the
/// framework's `MaterialLocalizations`, which since #8916 is a different type
/// from the one `material_ui` widgets look up — so on its own that list leaves
/// `MaterialApp` falling back to `DefaultMaterialLocalizations` and shipping
/// English Material strings to the other 21 locales. `DiVineAppBar`'s back
/// button reads `MaterialLocalizations.backButtonTooltip` for its semantic
/// label, so the regression would be silent and screen-reader-only.
///
/// The generated entries stay: third-party widgets still built on
/// `package:flutter/material.dart` resolve the framework types through them.
const List<LocalizationsDelegate<dynamic>> appLocalizationsDelegates =
    <LocalizationsDelegate<dynamic>>[
      ...AppLocalizations.localizationsDelegates,
      ...GlobalMaterialLocalizations.delegates,
    ];
